name: text
channels:
  - intel
  - defaults
dependencies:
  - pandas=1.3.4
  - matplotlib=3.5.0
  - numpy=1.21.2
  - nltk=3.6.5
  - ipykernel=6.6.0
  - scikit-learn=0.24.2
  - tqdm=4.62.3
  - ipywidgets=7.6.5
  - graphviz=2.38
  - pydot=1.4.1
  - pip:
    - absl-py==1.0.0
    - astunparse==1.6.3
    - cachetools==4.2.4
    - charset-normalizer==2.0.9
    - flatbuffers==2.0
    - gast==0.4.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - h5py==3.6.0
    - idna==3.3
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - libclang==12.0.0
    - markdown==3.3.6
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.27.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - termcolor==1.1.0
    - typing-extensions==4.0.1
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - zipp==3.7.0