name: text
channels:
  - intel
  - defaults
dependencies:
  - pandas=1.3.4
  - matplotlib=3.5.0
  - numpy=1.21.2
  - nltk=3.6.5
  - ipykernel=6.6.0
  - scikit-learn=0.24.2
  - tqdm=4.62.3
  - pip:
    - -r requirements.txt
